### ISSUE TITLE
Undo tree histiry sometimes lost!!

### ISSUE THREAD

**Issue by applejwjcat** [mbbill/undotree#115]
I meet the situations when the history may be deleted sometimes! Is there the operation that can delete the history automaticly? Like C-clang format ? Please give some advices? 

Then may because I load undotree lazily? I use dein to manage my vim plugins. This is my config 
```
    call dein#add('applejwjcat/undotree',{
        \ 'on_cmd': ['UndotreeFocus','UndotreeHide','UndotreeShow','UndotreeToggle'],
        \ 'on_event' : ['BufNewFile','BufReadPost'],
        \ 'hook_add' :'source $HOME/.config/nvim/modules/undotree.vim'
      \ })
```
and use plug I may load the plugin lazily too! (I create some auto_lazy_load function to manage all my plugins, to simplify the method, I just show how it works! Bur this is not actually my config)
```
call plug#begin(...)
     Plug 'mbbill/undotree', { 'on' : []}
call plug#end()

autocmd BufReadPre, BufNewFile * ++once call Load_undotree()
Function! Load_undotree()
 source '''my undotree config"
 call plug#load('undotree;)
EndFunction
```
Please give me some advices!

**Comment by mbbill** [comment]
I understand it might be pretty frustrating to lose some editing history, but I can sure you Undotree will not automatically delete history in any case.The plug-in is a fancy UI of **displaying** the internal undo tree rather than manipulating it.
In fact in Readme I encourage user to enable persistent undo history and put it into some safe place instead of default current folder.
You might want to double check the `undodir` setting. Its default value is `.` which means the undo history is saved in current folder and might get accidentally deleted by something like `git clean`.
Hope that helps.

**Comment by applejwjcat** [comment]
Thank you! I have found the solution! Thank you for the plugin, it save me lots of time!
