### ISSUE TITLE
Block mode insert broken while undotree pane is open

### ISSUE THREAD

**Issue by kainino0x** [mbbill/undotree#22]
Installed undotree with vundle. Seems to happen independently of any other options or plugins. Minimal .vimrc:

```
filetype off
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'mbbill/undotree'
```

Using insert in visual block mode results in incorrect text (but only when the undotree pane is open). Here's an example:

Original:

```
    v Cursor is here
#include <stdlib.h>
#include <unistd.h>
```

Command:

```
C-v j I <space> esc
```

Expected:

```
#inc lude <stdlib.h>
#inc lude <unistd.h>
```

Actual:

```
#inc lude <stdlib.h>
##include <unistd.h>
```

**Comment by thirtythreeforty** [comment]
I can't reproduce this under Arch.  My vimrc is admittedly [not minimal](github.com/thirtythreeforty/dotfiles) but if anything that should be further confirmation that this works OK.

**Comment by kainino0x** [comment]
Thanks for looking at this! I can confirm that I no longer experience this issue on Arch. My best guess is that there was an upstream bugfix in Vim. (?)

@mbbill I'll leave it up to you whether you want to close this report - I just tested the situation in your first reply, and it seems to still be an issue. (That is, there is different behavior when the undotree is open vs closed.)

**Comment by mbbill** [comment]
I believe it's a side behavior of the following lines:
```
let s:auEvents = "BufEnter,InsertLeave,CursorMoved,BufWritePost"
augroup Undotree
    exec "au! ".s:auEvents." * call UndotreeUpdate()"
augroup END
```
CursorMoved and InsertLeave would trigger an update to the undotree window which include a lot of window-jumping commands and result in a middle-state kept in history. 
Currently I'm not going to fix this since it doesn't seem to be too much of a problem, but binding events like insertleave and cursormoved is not a decent solution either, if there is any better way of keeping track of the content changes, I would be happy to apply it.
