### ISSUE TITLE
update alternate window when opening Undotree

### ISSUE THREAD

**Issue by Konfekt** [mbbill/undotree#54]
After `:UndoTreeToggle`, the alternate window number `winnr('#')` should be set to the window in which `:UndoTreeToggle` was called. Scripts may rely on this.

Instead `winnr('#')` is set to the preview window below the undotree.

**Comment by mbbill** [comment]
May I know which script rely on this?

**Comment by Konfekt** [comment]
My FastFold script gets confused about it. It cycles through all windows to update the folds of the current buffer and returns to the original window (and keeps track of the alternate window, that where `:UndoTree` was issued). 

However, Undotree changes the alternate window to the Diff window. Therefore the undo tree is that of the diff window, hence empty.

**Comment by mbbill** [comment]
I see.
This is because the undotree window will first update the diff windows and then draw itself. A sinple solution is just add two additional jumps, but it may trigger some unwanted behaviors like bufenter bufleave events and so on.
You may also try to use some other approach to remember the previous window rather than winnr(#)

**Comment by Konfekt** [comment]
Hmm..  I think what Undotree could do is use the prealternate  Window if the alternate  Window happens to be the diff window? The undotree of it never is of interest.

**Comment by Konfekt** [comment]
Resolved by putting `noautocmd` before `windo`.
