### ISSUE TITLE
Error while selecting from undo list

### ISSUE THREAD

**Issue by pdoak** [mbbill/undotree#58]
I have just started using undotree but it does't seem to be working properly. If I scroll through the undo list, the diff panel does not update. If I select a change and hit <Cr>, I get the following error:
```
Error detected while processing function <SNR>296_undotreeAction..471..475..472..491..486..501..502:
line   11:
E803: ID not found: 190890
```
After pressing <Cr> again, the diff panel updates with the change from the selected undo list.

I am running v 0.1.2-dev of Neovim on Mac OSX 10.11.2.

Thanks for your help.

**Comment by mbbill** [comment]
thanks for the bug report but unfortunately I couldn't reproduce it here, could you please try to disable all the plugins and try again? if the issue is still there, you may send me your vimrc and the test file.

**Comment by pdoak** [comment]
Thanks for you quick response.

I noticed that I had errors in my vimrc regarding the setting of the backup and undo directories. I have now fixed that and I no longer get any errors.

When I move through the undo tree, I still do not see the diff window updating until I hit the <CR> key. Is that how it should work because the ReadMe says Live updating of the diff panel.

Many Thanks

Paul

**Comment by mbbill** [comment]
Yeah, both the diff and main window won't get updated unless you actually switch to that version by hitting <cr> or a mouse click. it's because you can't get the diff without actually making an undo to that version, there is no something like 'preview a history version' in vim. But anyway, don't be afraid of losing anything as long as you don't save in that history version, and even if you saved, as long as you enabled the persistent undo, nothing would be lost.
